name: flutter_sdui_app
description: "A new Flutter project."

publish_to: 'none' # The default setting to prevent accidental publishing.

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.4'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.2.0

  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  
  # HTTP client
  dio: ^5.9.0
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # Internationalization
  intl: ^0.20.2

  # Local package for SDUI module
  sdui:
    path: ./packages/sdui

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  
  # Code generation
  json_serializable: ^6.11.1
  build_runner: ^2.7.1

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section below.
  assets:
    - assets/json/

  # To add fonts to your application, add a fonts section here.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
